/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.micwan88.moneytab;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class WebBotTest {
    @Test void webBotTest() {
        WebBot classUnderTest = new WebBot();
        assertNotNull(classUnderTest.dummyTest(), "Test");
    }
}
